### ISSUE TITLE
Trying to `cargo build` fails on `ui-sys`

### ISSUE THREAD

**Issue by heliasi4** [rust-native-ui/libui-rs#2]
Doing: `cargo build` causes following error on _Windows 7 (64bit)_ and _Rust 1.24_.

_Compiling ui-sys v0.1.1
error: failed to run custom build command for `ui-sys v0.1.1`

--- stderr
fatal: Not a git repository (or any of the parent directories): .git
thread 'main' panicked at '_

The trace leads to: `10: build_script_build::main at .\build.rs:15`

If I initialise a git-repo inside the folder, it just keeps the same error-trace but no actual mentioning of a fatal error.

**Comment by hummingly** [comment]
Running `cargo build` causes for me also an error on Windows 10 (64-bit) and Rust 1.24.

Compiling with ui-sys or iui returns:
error: failed to run custom build command for `ui-sys v0.1.1`
process didn't exit successfully: [...] (exit code: 101)

--- stderr
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 2, message: "Das System kann die angegebene Datei nicht finden." } }', src\libcore\result.rs:916:5

(Translation: "The system cannot find the specified file.")

**Comment by mark-summerfield** [comment]
I got the same problem on Windows 7-64-bit and Rust 1.25. I installed cmake-3.11.1 64-bit & I copied & pasted the example code into a new --bin project's src/main.rs and added `iui = "0.2"` to the Cargo.toml dependencies. Then I ran `cargo run --release`. The output was:
```
R:\rs\hellowin>cargo run --release --
    Updating registry `https://github.com/rust-lang/crates.io-index`
 Downloading iui v0.2.0
 Downloading ui-sys v0.1.1
 Downloading failure v0.1.1
 Downloading cmake v0.1.31
 Downloading make-cmd v0.1.0
 Downloading cc v1.0.15
 Downloading failure_derive v0.1.1
 Downloading backtrace v0.3.7
 Downloading synstructure v0.6.1
 Downloading rustc-demangle v0.1.8
 Downloading cfg-if v0.1.3
   Compiling make-cmd v0.1.0
   Compiling bitflags v0.7.0
   Compiling unicode-xid v0.0.4
   Compiling cfg-if v0.1.3
   Compiling cc v1.0.15
   Compiling winapi v0.3.4
   Compiling quote v0.3.15
   Compiling libc v0.2.40
   Compiling rustc-demangle v0.1.8
   Compiling synom v0.11.3
   Compiling syn v0.11.11
   Compiling backtrace v0.3.7
   Compiling cmake v0.1.31
   Compiling ui-sys v0.1.1
   Compiling synstructure v0.6.1
error: failed to run custom build command for `ui-sys v0.1.1` process didn't exit successfully: `R:\rs\hellowin\target\release\build\ui-sys-79acea2def35845c\build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "The system cannot find the file specified." }', libcore\result.rs:945:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.

warning: build failed, waiting for other jobs to finish...
error: build failed
```

**Comment by pgvee** [comment]
It's super ugly, but here is a patch to force it to build. 

There are a number of issues preventing compilation:

- CMakeLists has a set of incompatible MSVC options for a rust debug build
- the iui cargo.toml pulls from git instead of the local copy (so we can mangle it)
- the build.rs file in ui-sys fails in several places on windows
- linking fails because of a naming convention difference between windows and linux
- At the end of building a test project, the exe can't find teh libui.dll cause I suck at build scripts. I just manually moved it over.

[0001-Make-it-work-in-Windows.zip](https://github.com/LeoTindall/libui-rs/files/2020459/0001-Make-it-work-in-Windows.zip)

**Comment by NoraCodes** [comment]
Thanks for the patch. I'll incorporate it into my fixes.

**Comment by pgvee** [comment]
Oh gosh I was just thinking of easing the pain for folks who want to play. This isn't a PR, though it could be a starting point for one. 

On May 20, 2018 4:17:13 PM EDT, Leo Tindall <notifications@github.com> wrote:
>Thanks for the patch. I'll incorporate it into my fixes.
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/LeoTindall/libui-rs/issues/2#issuecomment-390508760

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by NoraCodes** [comment]
Recent push should have at least improved error messaging around this; can you retest?

**Comment by mark-summerfield** [comment]
I tried again, and it failed differently. I'm using Rust 1.26 on Win7-64. I installed CMake 3.11 and have the msvc tools needed by rustup & rust.
```
V:\tmp\guieg>cargo run
   Compiling unicode-xid v0.0.4
   Compiling winapi v0.3.4
   Compiling cc v1.0.15
   Compiling quote v0.3.15
   Compiling make-cmd v0.1.0
   Compiling cfg-if v0.1.3
   Compiling rustc-demangle v0.1.8
   Compiling libc v0.2.41
   Compiling bitflags v0.7.0
   Compiling synom v0.11.3
   Compiling cmake v0.1.31
   Compiling syn v0.11.11
   Compiling ui-sys v0.1.1
   Compiling backtrace v0.3.8
error: failed to run custom build command for `ui-sys v0.1.1`
process didn't exit successfully: `V:\tmp\guieg\target\debug\build\ui-sys-8e71083ecee36678\build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "The system cannot find the file specified." }', libcore\result.rs:945:5

warning: build failed, waiting for other jobs to finish...
error: build failed
```

**Comment by NoraCodes** [comment]
Could you try to build from master? The fixes aren't yet incorporated into the released version.

**Comment by pgvee** [comment]
Leo, I tried building again over my lunch hour and ran in to a few errors. I'm not at my dev PC ATM, so I can include more details later.  

There is still an (as in 1) unresolved link attempt to ui.lib, I noticed there are a few references in ui-sys/lib.rs & ui-sys/ffi.rs, though I have not yet figured how how many are trying to be linked against in my dummy program. 

Also, the build only seems to work on Release configuration due to this logic in ui-sys/build.rs
```
if msvc {
            postfix = postfix.join("Release");
}
```
which does not make the difference between build optimization levels. In the debug config, the line should be: 
```postfix = postfix.join("Debug");```

When I get some time later, I'll narrow it down a bit more. And yall have done such a good job making the source understandable, I might even be able to make some sort of PR-worthy attempt at this.

**Comment by NoraCodes** [comment]
Thanks for the input! I've fixed the MSVC debug/release issue in 1381342

A PR would be awesome, or even just more info about that failed link attempt.

**Comment by pgvee** [comment]
For sure. I'll work something up. We are super close.

On Wed, May 23, 2018, at 13:49, Leo Tindall wrote:
> Thanks for the input! I've fixed the MSVC debug/release issue
> in 1381342> A PR would be awesome, or even just more info about that failed link
> attempt.> — You are receiving this because you commented. Reply to this email
> directly, view it on GitHub[1], or mute the thread[2].

Links:

  1. https://github.com/LeoTindall/libui-rs/issues/2#issuecomment-391438831

**Comment by hummingly** [comment]
I've tried running the example at the readme with setting cargo.toml to the master branch. This time I get another error: "thread 'main' panicked at 'Unable to update libui submodule."

error: failed to run custom build command for `ui-sys v0.1.2 (https://github.com/LeoTindall/libui-rs#1381342f)`
process didn't exit successfully: `C:\Users\Chi\projects\playground\target\debug\build\ui-sys-0a480d19bdfedf86\build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at 'Unable to update libui submodule. Error: Os { code: 2, kind: NotFound, message: "Das System kann die angegebene Datei nicht finden." }', libcore\result.rs:945:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.

warning: build failed, waiting for other jobs to finish...
error: build failed

**Comment by NoraCodes** [comment]
Can you manually update the submodule? Do you have Git installed?

**Comment by huangjj27** [comment]
I retried building the example on README by changing the `iui` dependency:

```toml
# cargo.toml

[dependencies]
iui = { git = "https://github.com/LeoTindall/libui-rs", branch = "master" }
```

and clean up with `cargo clean`.

However, I still get some error:
```shell
error: failed to run custom build command for `ui-sys v0.1.2 (https://github.com/LeoTindall/libui-rs#1381342f)`
process didn't exit successfully: `C:\Users\34937\Desktop\learning-rust\iui-example\target\debug\build\ui-sys-7c93db0a6a2acda5\build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at '
command did not execute successfully, got: exit code: 1

build script failed, must exit now', C:\Users\34937\.cargo\registry\src\mirrors.ustc.edu.cn-61ef6e0cd06fb9b8\cmake-0.1.31\src\lib.rs:643:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

I was compiling with `rust-nigitly-2018-05-14-x86_64-msvc` on win10

**Comment by pgvee** [comment]
Yes, it's still broken.

For the time being, if you add --release, it should build.

It's broken because cmakes builder selects the wrong msvc configuration of libui, which automatically adds an incompatible compiler flag to the libui debug build specification.

Libui maintainers are also frustrated with this behavior. I'm looking in to ways circumvent the issue. 

On May 23, 2018 10:33:46 PM EDT, Junjie Huang <notifications@github.com> wrote:
>I retry to build the example on README by changing the `iui`
>dependency:
>
>```toml
># cargo.toml
>
>[dependencies]
>iui = { git = "https://github.com/LeoTindall/libui-rs", branch =
>"master" }
>```
>
>and clean up with `cargo clean`.
>
>However, I still get some error:
>```shell
>error: failed to run custom build command for `ui-sys v0.1.2
>(https://github.com/LeoTindall/libui-rs#1381342f)`
>process didn't exit successfully:
>`C:\Users\34937\Desktop\learning-rust\iui-example\target\debug\build\ui-sys-7c93db0a6a2acda5\build-script-build`
>(exit code: 101)
>--- stderr
>thread 'main' panicked at '
>command did not execute successfully, got: exit code: 1
>
>build script failed, must exit now',
>C:\Users\34937\.cargo\registry\src\mirrors.ustc.edu.cn-61ef6e0cd06fb9b8\cmake-0.1.31\src\lib.rs:643:5
>note: Run with `RUST_BACKTRACE=1` for a backtrace.
>```
>
>I was compiling with `rust-nigitly-2018-05-14-x86_64-msvc`
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/LeoTindall/libui-rs/issues/2#issuecomment-391568260

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by mark-summerfield** [comment]
I tried the example app and this time it built iui-sys 0.1.3 and iui 0.3.0 worked fine (Win-7-64, Rust 1.26.2). I'll now start trying it out properly.

**Comment by abienz** [comment]
I'm getting this error again with latest iui "0.3" and latest Rust, has there been a regression?

`
fatal: not a git repository (or any of the parent directories): .git
CMake Error at /usr/local/Cellar/cmake/3.13.3/share/cmake/Modules/CMakeTestCXXCompiler.cmake:45 (message):
  The C++ compiler

    "/usr/bin/c++"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: /Users/abienz/Workspace/test_ui/target/debug/build/ui-sys-98391fb19ec9b552/out/build/CMakeFiles/CMakeTmp

    Run Build Command:"/usr/bin/make" "cmTC_9aa41/fast"
    /Library/Developer/CommandLineTools/usr/bin/make -f CMakeFiles/cmTC_9aa41.dir/build.make CMakeFiles/cmTC_9aa41.dir/build
    Building CXX object CMakeFiles/cmTC_9aa41.dir/testCXXCompiler.cxx.o
    /usr/bin/c++    -ffunction-sections -fdata-sections -fPIC -m64  -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk -mmacosx-version-min=10.8   -o CMakeFiles/cmTC_9aa41.dir/testCXXCompiler.cxx.o -c /Users/abienz/Workspace/test_ui/target/debug/build/ui-sys-98391fb19ec9b552/out/build/CMakeFiles/CMakeTmp/testCXXCompiler.cxx
    warning: include path for stdlibc++ headers not found; pass '-std=libc++' on the command line to use the libc++ standard library instead [-Wstdlibcxx-not-found]
    1 warning generated.
    Linking CXX executable cmTC_9aa41
    /usr/local/Cellar/cmake/3.13.3/bin/cmake -E cmake_link_script CMakeFiles/cmTC_9aa41.dir/link.txt --verbose=1
    /usr/bin/c++   -ffunction-sections -fdata-sections -fPIC -m64  -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk -mmacosx-version-min=10.8 -Wl,-search_paths_first -Wl,-headerpad_max_install_names   CMakeFiles/cmTC_9aa41.dir/testCXXCompiler.cxx.o  -o cmTC_9aa41
    clang: warning: libstdc++ is deprecated; move to libc++ with a minimum deployment target of OS X 10.9 [-Wdeprecated]
    ld: library not found for -lstdc++
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    make[1]: *** [cmTC_9aa41] Error 1
    make: *** [cmTC_9aa41/fast] Error 2
`

**Comment by barzamin** [comment]
this is a known issue on modern macOS (#38); i wrote a patch (#59) which unfortunately hasn't been reviewed yet

**Comment by villisek** [comment]
Hello, 

I can also confirm the problem is still here on Windows 7 x64. On compile (with or without "--release"), I get this :
```
   Compiling ui-sys v0.2.1 (https://github.com/rust-native-ui/libui-rs.git?branc
h=trunk#6ff94425)
error: failed to run custom build command for `ui-sys v0.2.1 (https://github.com
/rust-native-ui/libui-rs.git?branch=trunk#6ff94425)`

Caused by:
  process didn't exit successfully: `C:\Users\CLEMENT\Documents\grapherval\targe
t\release\build\ui-sys-761e9f7870310257\build-script-build` (exit code: 101)
  --- stderr
  thread 'main' panicked at 'Unable to update libui submodule. Error: Os { code:
 2, kind: NotFound, message: "Le fichier spécifié est introuvable." }', C:\Users
\CLEMENT\.cargo\git\checkouts\libui-rs-e12bbe2e66777697\6ff9442\ui-sys\build.rs:
36:18
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
(the file can't be found...)

Trying to compile with MinGW instead of MSVC gives the exact same error.
